### ISSUE TITLE
Current Location

### ISSUE THREAD

**Issue by velcis** [cabify/api-docs#24]
I cant use current location at Stop array, is this? "stops":[ { "loc" : "current" }

Not working!

**Comment by hugocbpassos** [comment]
According to the docs: 

> You can also set the first stop as the string “current”, in which case the app will grab the user location and use that as origin

Indeed, `{ "loc" : "current" }` does nothing. Besided, passing just `"current"` results in an infinite loading.

Anyway, no example was provided, so we are in the dark here.

It's also interesting to see how long ago this issue has been opened, and cabify team gave actual 0 fucks.

@michaelkoper @samlown  @arctarus @Elgranchorla @keyvanakbary @gguerrero @bernardo-martinez @nicolasgarnil @jmcervera @ciscou @rramonfraga @patriciagao @palcalde

**Comment by bernardo-martinez** [comment]
we are currently updating estimator and sending `current` doesn't work so you should send start location. Will notify you whenever it is back.
Format should be: `cabify:///journey?json={"vehicle_type":"product_id","stops":["current",{"loc":{"latitude":40.4417,"longitude":-3.1112}}]}`
